const ActionType = {
ADD_PATEINT:'ADD_PATEINT',
ADD_PATEINTSUCCESS:'ADD_PATEINTSUCCESS',
VIEW_PATEINT:'VIEW_PATEINT',
VIEW_PATEINTSUCCESS:'VIEW_PATEINTSUCCESS',
DEL_PATEINT:'DEL_PATEINT',
DEL_PATEINTSUCCESS:'DEL_PATEINTSUCCESS',

}


export default ActionType;